#version 450

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer InputBuffer {
    vec2 inArray[];
};
layout (set = 0, binding = 1) buffer OutputBuffer {
    vec2 outArray[];
};

layout(set = 0, binding = 2)  buffer IndexBuffer {
    uint[] index_buffer;
};

void main(void){
    uint global_ix = gl_GlobalInvocationID.x;
    outArray[global_ix] = inArray[index_buffer[global_ix]];
}
