//
// Created by Marcin on 18.05.2020.
//

#ifndef VULKANSTREAMREDUCE_VULKAN_ASSERTION_ERROR_H
#define VULKANSTREAMREDUCE_VULKAN_ASSERTION_ERROR_H


class vulkan_assertion_error {

};


#endif //VULKANSTREAMREDUCE_VULKAN_ASSERTION_ERROR_H
